### ISSUE TITLE
slurm template doesn't work with looper lump

### ISSUE THREAD

**Issue by nsheff** [pepkit/pepenv#2]
The local template works with `looper` `--lump`. the slurm template, though, will only add `srun` to the first command.

**Comment by vreuter** [comment]
Has this been addressed? I recall something similar, but can't remember if it was this particular thing that was solved, or if this is separate.

**Comment by nsheff** [comment]
I believe this has *not* been addressed. It may be as simple as changing the slurm template to:

```
srun {
{CODE}
} 
```

**Comment by vreuter** [comment]
OK

**Comment by nsheff** [comment]
it ended up being a bit more complicated than that...
