### ISSUE TITLE
Error (maybe) in readme

### ISSUE THREAD

**Issue by rcorces** [pepkit/pepenv#5]
Just reading through some of this README. I think there is an error in the example Slurm template in the README section.
From the section titled "Templates Files" (probably should be "template files" but thats a separate point?) the code should read "srun {CODE}" rather than just "{CODE}". You might also want to check the slurm_sig_template.sub which may need to be updated with "srun" as well?

Screenshot below. 

![image](https://user-images.githubusercontent.com/10343046/41386892-d69ca5f0-6f38-11e8-896f-af45225e88d3.png)

**Comment by vreuter** [comment]
Good call, thanks @rcorces . Fixed in https://github.com/pepkit/pepenv/commit/d5f86fbdbf39d1ffc8fd2496a784120d11e76f7a

**Comment by nsheff** [comment]
thanks.

for the slurm_sig_template...that was mostly a testing thing. it's never really been actively used. I should probably just delete it...
